import { makeDecomposed, makeFinalOnly, type Decomposed } from "./hangul";

export const kanaToHangul = new Map([
  // hiragana
  ["あ", "아"],
  ["い", "이"],
  ["う", "우"],
  ["え", "에"],
  ["お", "오"],
  ["か", "카"],
  ["き", "키"],
  ["く", "쿠"],
  ["け", "케"],
  ["こ", "코"],
  ["が", "가"],
  ["ぎ", "기"],
  ["ぐ", "구"],
  ["げ", "게"],
  ["ご", "고"],
  ["さ", "사"],
  ["し", "시"],
  ["す", "스"],
  ["せ", "세"],
  ["そ", "소"],
  ["ざ", "자"],
  ["じ", "지"],
  ["ず", "즈"],
  ["ぜ", "제"],
  ["ぞ", "조"],
  ["た", "타"],
  ["ち", "치"],
  ["つ", "츠"],
  ["て", "테"],
  ["と", "토"],
  ["だ", "다"],
  ["ぢ", "지"],
  ["づ", "즈"],
  ["で", "데"],
  ["ど", "도"],
  ["な", "나"],
  ["に", "니"],
  ["ぬ", "누"],
  ["ね", "네"],
  ["の", "노"],
  ["は", "하"],
  ["ひ", "히"],
  ["ふ", "후"],
  ["へ", "헤"],
  ["ほ", "호"],
  ["ば", "바"],
  ["び", "비"],
  ["ぶ", "부"],
  ["べ", "베"],
  ["ぼ", "보"],
  ["ぱ", "파"],
  ["ぴ", "피"],
  ["ぷ", "푸"],
  ["ぺ", "페"],
  ["ぽ", "포"],
  ["ま", "마"],
  ["み", "미"],
  ["む", "무"],
  ["め", "메"],
  ["も", "모"],
  ["や", "야"],
  ["ゆ", "유"],
  ["よ", "요"],
  ["ら", "라"],
  ["り", "리"],
  ["る", "루"],
  ["れ", "레"],
  ["ろ", "로"],
  ["わ", "와"],
  ["を", "오"],
  ["ん", "응"],

  // katakana
  ["ア", "아"],
  ["イ", "이"],
  ["ウ", "우"],
  ["エ", "에"],
  ["オ", "오"],
  ["カ", "카"],
  ["キ", "키"],
  ["ク", "쿠"],
  ["ケ", "케"],
  ["コ", "코"],
  ["ガ", "가"],
  ["ギ", "기"],
  ["グ", "구"],
  ["ゲ", "게"],
  ["ゴ", "고"],
  ["サ", "사"],
  ["シ", "시"],
  ["ス", "스"],
  ["セ", "세"],
  ["ソ", "소"],
  ["ザ", "자"],
  ["ジ", "지"],
  ["ズ", "즈"],
  ["ゼ", "제"],
  ["ゾ", "조"],
  ["タ", "타"],
  ["チ", "치"],
  ["ツ", "츠"],
  ["テ", "테"],
  ["ト", "토"],
  ["ダ", "다"],
  ["ヂ", "지"],
  ["ヅ", "즈"],
  ["デ", "데"],
  ["ド", "도"],
  ["ナ", "나"],
  ["ニ", "니"],
  ["ヌ", "누"],
  ["ネ", "네"],
  ["ノ", "노"],
  ["ハ", "하"],
  ["ヒ", "히"],
  ["フ", "후"],
  ["ヘ", "헤"],
  ["ホ", "호"],
  ["バ", "바"],
  ["ビ", "비"],
  ["ブ", "부"],
  ["ベ", "베"],
  ["ボ", "보"],
  ["パ", "파"],
  ["ピ", "피"],
  ["プ", "푸"],
  ["ペ", "페"],
  ["ポ", "포"],
  ["マ", "마"],
  ["ミ", "미"],
  ["ム", "무"],
  ["メ", "메"],
  ["モ", "모"],
  ["ヤ", "야"],
  ["ユ", "유"],
  ["ヨ", "요"],
  ["ラ", "라"],
  ["リ", "리"],
  ["ル", "루"],
  ["レ", "레"],
  ["ロ", "로"],
  ["ワ", "와"],
  ["ヲ", "오"],
  ["ン", "응"],
  ["ヴ", "브"],
]);

export const suteganaToHangul = new Map<string, Decomposed>([
  // hiragana
  ["ぁ", makeDecomposed("", "ㅏ", "")],
  ["ぃ", makeDecomposed("", "ㅣ", "")],
  ["ぅ", makeDecomposed("", "ㅜ", "")],
  ["ぇ", makeDecomposed("", "ㅔ", "")],
  ["ぉ", makeDecomposed("", "ㅗ", "")],
  ["ゃ", makeDecomposed("", "ㅑ", "")],
  ["ゅ", makeDecomposed("", "ㅠ", "")],
  ["ょ", makeDecomposed("", "ㅛ", "")],
  ["ゎ", makeDecomposed("", "ㅘ", "")],
  ["っ", makeDecomposed("", "", "ㅅ")],

  // katakana
  ["ァ", makeDecomposed("", "ㅏ", "")],
  ["ィ", makeDecomposed("", "ㅣ", "")],
  ["ゥ", makeDecomposed("", "ㅜ", "")],
  ["ェ", makeDecomposed("", "ㅔ", "")],
  ["ォ", makeDecomposed("", "ㅗ", "")],
  ["ャ", makeDecomposed("", "ㅑ", "")],
  ["ュ", makeDecomposed("", "ㅠ", "")],
  ["ョ", makeDecomposed("", "ㅛ", "")],
  ["ヮ", makeDecomposed("", "ㅘ", "")],
  ["ッ", makeDecomposed("", "", "ㅅ")],
]);

export const suteganaMergeTable = new Map([
  // 直音 (y, wを用いない)
  ["スィ", makeDecomposed("ㅅ", "ㅣ", "")],
  ["シェ", makeDecomposed("ㅅ", "ㅔ", "")],
  ["ティ", makeDecomposed("ㅌ", "ㅣ", "")],
  ["トゥ", makeDecomposed("ㅌ", "ㅜ", "")],
  ["チェ", makeDecomposed("ㅊ", "ㅔ", "")],
  ["ツァ", makeDecomposed("ㅊ", "ㅏ", "")],
  ["ツィ", makeDecomposed("ㅊ", "ㅣ", "")],
  ["ツェ", makeDecomposed("ㅊ", "ㅔ", "")],
  ["ツォ", makeDecomposed("ㅊ", "ㅗ", "")],
  ["ホゥ", makeDecomposed("ㅎ", "ㅜ", "")],
  ["ファ", makeDecomposed("ㅎ", "ㅏ", "")],
  ["フィ", makeDecomposed("ㅎ", "ㅣ", "")],
  ["フェ", makeDecomposed("ㅎ", "ㅔ", "")],
  ["フォ", makeDecomposed("ㅎ", "ㅗ", "")],
  ["ズィ", makeDecomposed("ㅈ", "ㅣ", "")],
  ["ジェ", makeDecomposed("ㅈ", "ㅔ", "")],
  ["ディ", makeDecomposed("ㄷ", "ㅣ", "")],
  ["ドゥ", makeDecomposed("ㄷ", "ㅜ", "")],
  ["ヴァ", makeDecomposed("ㅂ", "ㅏ", "")],
  ["ヴィ", makeDecomposed("ㅂ", "ㅣ", "")],
  ["ヴェ", makeDecomposed("ㅂ", "ㅔ", "")],
  ["ヴォ", makeDecomposed("ㅂ", "ㅗ", "")],
  // 開拗音 (yを用いる)
  ["イェ", makeDecomposed("ㅇ", "ㅖ", "")],
  ["キェ", makeDecomposed("ㅋ", "ㅖ", "")],
  ["スャ", makeDecomposed("ㅅ", "ㅑ", "")],
  ["スュ", makeDecomposed("ㅅ", "ㅠ", "")],
  ["スョ", makeDecomposed("ㅅ", "ㅛ", "")],
  ["テャ", makeDecomposed("ㅌ", "ㅑ", "")],
  ["テュ", makeDecomposed("ㅌ", "ㅠ", "")],
  ["テョ", makeDecomposed("ㅌ", "ㅛ", "")],
  ["ツャ", makeDecomposed("ㅊ", "ㅑ", "")],
  ["ツュ", makeDecomposed("ㅊ", "ㅠ", "")],
  ["ツョ", makeDecomposed("ㅊ", "ㅛ", "")],
  ["ニェ", makeDecomposed("ㄴ", "ㅖ", "")],
  ["ヒェ", makeDecomposed("ㅎ", "ㅖ", "")],
  ["フャ", makeDecomposed("ㅎ", "ㅑ", "")],
  ["フュ", makeDecomposed("ㅎ", "ㅠ", "")],
  ["フョ", makeDecomposed("ㅎ", "ㅛ", "")],
  ["ピェ", makeDecomposed("ㅍ", "ㅖ", "")],
  ["ミェ", makeDecomposed("ㅁ", "ㅖ", "")],
  ["リェ", makeDecomposed("ㄹ", "ㅖ", "")],
  ["ギェ", makeDecomposed("ㄱ", "ㅖ", "")],
  ["ズャ", makeDecomposed("ㅈ", "ㅑ", "")],
  ["ズュ", makeDecomposed("ㅈ", "ㅠ", "")],
  ["ズョ", makeDecomposed("ㅈ", "ㅛ", "")],
  ["デャ", makeDecomposed("ㄷ", "ㅑ", "")],
  ["デュ", makeDecomposed("ㄷ", "ㅠ", "")],
  ["デョ", makeDecomposed("ㄷ", "ㅛ", "")],
  ["ヴャ", makeDecomposed("ㅂ", "ㅑ", "")],
  ["ヴュ", makeDecomposed("ㅂ", "ㅠ", "")],
  ["ヴョ", makeDecomposed("ㅂ", "ㅛ", "")],
  ["ビェ", makeDecomposed("ㅂ", "ㅖ", "")],
  // 合拗音 (wを用いる)
  ["ウィ", makeDecomposed("ㅇ", "ㅟ", "")],
  ["ウェ", makeDecomposed("ㅇ", "ㅞ", "")],
  ["ウォ", makeDecomposed("ㅇ", "ㅝ", "")],
  ["クァ", makeDecomposed("ㅋ", "ㅘ", "")],
  ["クヮ", makeDecomposed("ㅋ", "ㅘ", "")],
  ["クィ", makeDecomposed("ㅋ", "ㅟ", "")],
  ["クェ", makeDecomposed("ㅋ", "ㅞ", "")],
  ["クォ", makeDecomposed("ㅋ", "ㅝ", "")],
  ["スァ", makeDecomposed("ㅅ", "ㅘ", "")],
  ["スヮ", makeDecomposed("ㅅ", "ㅘ", "")],
  ["スェ", makeDecomposed("ㅅ", "ㅞ", "")],
  ["スォ", makeDecomposed("ㅅ", "ㅝ", "")],
  ["ヌァ", makeDecomposed("ㄴ", "ㅘ", "")],
  ["ヌヮ", makeDecomposed("ㄴ", "ㅘ", "")],
  ["ヌィ", makeDecomposed("ㄴ", "ㅟ", "")],
  ["ヌェ", makeDecomposed("ㄴ", "ㅞ", "")],
  ["ヌォ", makeDecomposed("ㄴ", "ㅝ", "")],
  ["プァ", makeDecomposed("ㅍ", "ㅘ", "")],
  ["プヮ", makeDecomposed("ㅍ", "ㅘ", "")],
  ["プィ", makeDecomposed("ㅍ", "ㅟ", "")],
  ["プェ", makeDecomposed("ㅍ", "ㅞ", "")],
  ["プォ", makeDecomposed("ㅍ", "ㅝ", "")],
  ["ムァ", makeDecomposed("ㅁ", "ㅘ", "")],
  ["ムヮ", makeDecomposed("ㅁ", "ㅘ", "")],
  ["ムィ", makeDecomposed("ㅁ", "ㅟ", "")],
  ["ムェ", makeDecomposed("ㅁ", "ㅞ", "")],
  ["ムォ", makeDecomposed("ㅁ", "ㅝ", "")],
  ["ルァ", makeDecomposed("ㄹ", "ㅘ", "")],
  ["ルヮ", makeDecomposed("ㄹ", "ㅘ", "")],
  ["ルィ", makeDecomposed("ㄹ", "ㅟ", "")],
  ["ルェ", makeDecomposed("ㄹ", "ㅞ", "")],
  ["ルォ", makeDecomposed("ㄹ", "ㅝ", "")],
  ["グァ", makeDecomposed("ㄱ", "ㅘ", "")],
  ["グヮ", makeDecomposed("ㄱ", "ㅘ", "")],
  ["グィ", makeDecomposed("ㄱ", "ㅟ", "")],
  ["グェ", makeDecomposed("ㄱ", "ㅞ", "")],
  ["グォ", makeDecomposed("ㄱ", "ㅝ", "")],
  ["ズァ", makeDecomposed("ㅈ", "ㅘ", "")],
  ["ズヮ", makeDecomposed("ㅈ", "ㅘ", "")],
  ["ズェ", makeDecomposed("ㅈ", "ㅞ", "")],
  ["ズォ", makeDecomposed("ㅈ", "ㅝ", "")],
  ["ブァ", makeDecomposed("ㅂ", "ㅘ", "")],
  ["ブヮ", makeDecomposed("ㅂ", "ㅘ", "")],
  ["ブィ", makeDecomposed("ㅂ", "ㅟ", "")],
  ["ブェ", makeDecomposed("ㅂ", "ㅞ", "")],
  ["ブォ", makeDecomposed("ㅂ", "ㅝ", "")],
  // 드물지만 존재하는 경우
  ["スィェ", makeDecomposed("ㅅ", "ㅖ", "")],
  ["ティェ", makeDecomposed("ㅌ", "ㅖ", "")],
  ["ツィェ", makeDecomposed("ㅊ", "ㅖ", "")],
  ["フィェ", makeDecomposed("ㅎ", "ㅖ", "")],
  ["ズィェ", makeDecomposed("ㅈ", "ㅖ", "")],
  ["ディェ", makeDecomposed("ㄷ", "ㅖ", "")],
  ["ヴィェ", makeDecomposed("ㅂ", "ㅖ", "")],
  ["シュァ", makeDecomposed("ㅅ", "ㅘ", "")],
  ["シヮ", makeDecomposed("ㅅ", "ㅘ", "")],
  ["シュィ", makeDecomposed("ㅅ", "ㅟ", "")],
  ["シュェ", makeDecomposed("ㅅ", "ㅞ", "")],
  ["シュォ", makeDecomposed("ㅅ", "ㅝ", "")],
  ["トゥァ", makeDecomposed("ㅌ", "ㅘ", "")],
  ["トァ", makeDecomposed("ㅌ", "ㅘ", "")],
  ["トヮ", makeDecomposed("ㅌ", "ㅘ", "")],
  ["トゥィ", makeDecomposed("ㅌ", "ㅟ", "")],
  ["トィ", makeDecomposed("ㅌ", "ㅟ", "")],
  ["トゥェ", makeDecomposed("ㅌ", "ㅞ", "")],
  ["トェ", makeDecomposed("ㅌ", "ㅞ", "")],
  ["トゥォ", makeDecomposed("ㅌ", "ㅝ", "")],
  ["チュァ", makeDecomposed("ㅊ", "ㅘ", "")],
  ["チヮ", makeDecomposed("ㅊ", "ㅘ", "")],
  ["チュィ", makeDecomposed("ㅊ", "ㅟ", "")],
  ["チュェ", makeDecomposed("ㅊ", "ㅞ", "")],
  ["チュォ", makeDecomposed("ㅊ", "ㅝ", "")],
  ["ホゥァ", makeDecomposed("ㅎ", "ㅘ", "")],
  ["ホヮ", makeDecomposed("ㅎ", "ㅘ", "")],
  ["ホゥィ", makeDecomposed("ㅎ", "ㅟ", "")],
  ["ホゥェ", makeDecomposed("ㅎ", "ㅞ", "")],
  ["ホゥォ", makeDecomposed("ㅎ", "ㅝ", "")],
  ["ジュァ", makeDecomposed("ㅈ", "ㅘ", "")],
  ["ジヮ", makeDecomposed("ㅈ", "ㅘ", "")],
  ["ジュィ", makeDecomposed("ㅈ", "ㅟ", "")],
  ["ジュェ", makeDecomposed("ㅈ", "ㅞ", "")],
  ["ジュォ", makeDecomposed("ㅈ", "ㅝ", "")],
  ["ドゥァ", makeDecomposed("ㄷ", "ㅘ", "")],
  ["ドァ", makeDecomposed("ㄷ", "ㅘ", "")],
  ["ドヮ", makeDecomposed("ㄷ", "ㅘ", "")],
  ["ドゥィ", makeDecomposed("ㄷ", "ㅟ", "")],
  ["ドィ", makeDecomposed("ㄷ", "ㅟ", "")],
  ["ドゥェ", makeDecomposed("ㄷ", "ㅞ", "")],
  ["ドェ", makeDecomposed("ㄷ", "ㅞ", "")],
  ["ドゥォ", makeDecomposed("ㄷ", "ㅝ", "")],
]);

export const isFull = (char: string) => kanaToHangul.get(char) != null;
export const isSutegana = (char: string) => suteganaToHangul.get(char) != null;
export const isNN = (char: string) => char == "ン" || char == "ん";

const soundN = makeFinalOnly("ㄴ");
// const soundNg = makeFinalOnly("ㅇ");
// const soundM = makeFinalOnly("ㅁ");
// const nasalSounds = new Map([
//   ["さ", soundN],
//   ["ざ", soundN],
//   ["た", soundN],
//   ["だ", soundN],
//   ["な", soundN],
//   ["ら", soundN],
//   ["ば", soundM],
//   ["ぱ", soundM],
//   ["ま", soundM],
//   ["か", soundNg],
//   ["が", soundNg],
//   ["あ", soundN],
//   ["は", soundN],
//   ["や", soundN],
//   ["わ", soundN],
//   ["サ", soundN],
//   ["ザ", soundN],
//   ["タ", soundN],
//   ["ダ", soundN],
//   ["ナ", soundN],
//   ["ラ", soundN],
//   ["バ", soundM],
//   ["パ", soundM],
//   ["マ", soundM],
//   ["カ", soundNg],
//   ["ガ", soundNg],
//   ["ア", soundN],
//   ["ハ", soundN],
//   ["ヤ", soundN],
//   ["ワ", soundN],
// ]);

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const getNasalSound = (char: string) => soundN;

// export function getNasalSound(char: string) {
//   const sound = nasalSounds.get(char);
//   if (sound != null) return sound;
//   return soundN;
// }

export function hiraganaToKatakana(hiragana: string) {
  return hiragana.replaceAll(/[ぁ-ゖ]/gu, (x) => String.fromCharCode(x.charCodeAt(0) + 96));
}
